// console.log(board[2][0])
// console.log(board[3][1])
// console.log(board[4][2])
// console.log(board[5][3])

// console.log(board[1][0])
// console.log(board[2][1])
// console.log(board[3][2])
// console.log(board[4][3])
// console.log(board[5][4])

// console.log(board[0][0])
// console.log(board[1][1])
// console.log(board[2][2])
// console.log(board[3][3])
// console.log(board[4][4])
// console.log(board[5][5])

// console.log(board[0][1])
// console.log(board[1][2])
// console.log(board[2][3])
// console.log(board[3][4])
// console.log(board[4][5])
// console.log(board[5][6])

// console.log(board[0][2])
// console.log(board[1][3])
// console.log(board[2][4])
// console.log(board[3][5])
// console.log(board[4][6])

// console.log(board[0][3])
// console.log(board[1][4])
// console.log(board[2][5])
// console.log(board[3][6])